from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register_view, name='register'),
    path('products/', views.product_list, name='product_list'),
    path('products/add/', views.product_create, name='product_create'),
    path('products/<int:pk>/edit/', views.product_update, name='product_update'),
    path('products/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('products/<int:pk>/increase/', views.product_increase_stock, name='product_increase_stock'),
    path('products/<int:pk>/decrease/', views.product_decrease_stock, name='product_decrease_stock'),
    path('products/<int:pk>/history/', views.stock_history, name='stock_history'),
    path('stock-movements/', views.all_stock_movements, name='all_stock_movements'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/add/', views.customer_create, name='customer_create'),
    path('customers/<int:pk>/edit/', views.customer_update, name='customer_update'),
    path('customers/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('sales/', views.sale_list, name='sale_list'),
    path('sales/new/', views.sale_create, name='sale_create'),
    path('sales/<int:pk>/', views.sale_detail, name='sale_detail'),
    path('products/intake/', views.product_intake, name='product_intake'),
    path('products/import/', views.product_import, name='product_import'),
    path('products/import/template/', views.product_import_template, name='product_import_template'),
    path('api/product-search/', views.product_search, name='product_search'),
    path('api/barcode/<str:code>/', views.barcode_lookup, name='barcode_lookup'),
    path('reference/import/', views.reference_import, name='reference_import'),
    path('reference/import/template/', views.reference_import_template, name='reference_import_template'),
    path('update/', views.update_app, name='update_app'),
    path('restart/', views.restart_app, name='restart_app'),
]
