# Generated by Django 6.0.4 on 2026-04-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('category', models.CharField(max_length=255, verbose_name='Kategori')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Üretici')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stok Miktarı')),
                ('unit', models.CharField(default='adet', max_length=50, verbose_name='Birim')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='Barkod')),
                ('tax_rate', models.FloatField(default=20.0, verbose_name='KDV Oranı (%)')),
                ('supplier', models.CharField(blank=True, default='', max_length=255, verbose_name='Tedarikçi')),
                ('shelf_location', models.CharField(blank=True, default='', max_length=50, verbose_name='Raf Konumu')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Minimum Stok')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField(verbose_name='Değişim Miktarı')),
                ('old_stock', models.IntegerField(verbose_name='Eski Stok')),
                ('new_stock', models.IntegerField(verbose_name='Yeni Stok')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Not')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Ürün')),
            ],
        ),
    ]
