# Generated by Django 6.0.4 on 2026-04-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('tax_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Tax Number')),
                ('contact_person', models.CharField(blank=True, default='', max_length=255, verbose_name='Contact Person')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='Minimum Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_location',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Shelf Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.FloatField(default=20.0, verbose_name='Tax Rate (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='adet', max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='change_amount',
            field=models.IntegerField(verbose_name='Change Amount'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='new_stock',
            field=models.IntegerField(verbose_name='New Stock'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='old_stock',
            field=models.IntegerField(verbose_name='Old Stock'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Product'),
        ),
    ]
