# Generated by Django 6.0.4 on 2026-04-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Shop Name'),
        ),
    ]
