# Generated by Django 6.0.4 on 2026-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_customer_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt',
            field=models.FloatField(default=0.0, verbose_name='Debt (₺)'),
        ),
    ]
