# Generated by Django 6.0.4 on 2026-04-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_customer_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Due Date'),
        ),
    ]
