# Generated by Django 6.0.4 on 2026-06-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_sale_saleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Barcode')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255, verbose_name='Manufacturer')),
                ('category', models.CharField(blank=True, default='', max_length=255, verbose_name='Category')),
                ('unit', models.CharField(blank=True, default='adet', max_length=50, verbose_name='Unit')),
                ('tax_rate', models.FloatField(default=20.0, verbose_name='Tax Rate (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
