# Generated by Django 6.0.4 on 2026-08-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_referencebarcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_tracking_enabled', models.BooleanField(default=True, verbose_name='Stock Tracking')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True, verbose_name='Track Stock'),
        ),
    ]
