# Generated by Django 6.0.4 on 2026-08-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_appsetting_product_track_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Manufacturer'),
        ),
    ]
