# Generated by Django 6.0.4 on 2026-08-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_category_alter_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cancel Reason'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancelled'),
        ),
    ]
