# Generated by Django 6.0.4 on 2026-08-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_sale_cancel_reason_sale_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='default_markup_percent',
            field=models.FloatField(default=35.0, verbose_name='Default Markup (%)'),
        ),
    ]
