# Generated by Django 6.0.4 on 2026-08-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_appsetting_default_markup_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.FloatField(default=0, verbose_name='Min Purchase Price')),
                ('max_price', models.FloatField(blank=True, null=True, verbose_name='Max Purchase Price')),
                ('percent', models.FloatField(default=35.0, verbose_name='Markup (%)')),
                ('flat_addition', models.FloatField(default=0.0, verbose_name='Flat Addition (₺)')),
            ],
            options={
                'ordering': ['min_price'],
            },
        ),
    ]
